#spring:
#  application:
#    name: project-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/project_service_databases?createTableIfNotExist=true
#    username: root
#    password: 8dipakR0@
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql://localhost:3306/project_service_databases?createTableIfNotExist=true
    username: root
    password: 8dipakR0@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/